/*
  This file contains the sequence of stimulus values and the specification for the main sequence.
  The sequence of stimulus values is generated by the sequence generator.
*/

import { MAIN_TRIALS_PER_BLOCK, NUMEROSITY_MAX, NUMEROSITY_MIN } from "../config.js";
import { circularError} from "../utils.js";

export const MAIN_SEQUENCE_DIFF_COUNT = MAIN_TRIALS_PER_BLOCK - 1;
export const DIFFERENCE_BINS_PER_FACTOR = 5;
export const DIFFERENCES_PER_BIN = MAIN_SEQUENCE_DIFF_COUNT / DIFFERENCE_BINS_PER_FACTOR;
export const TARGET_SIGN_COUNT_PER_BIN = DIFFERENCES_PER_BIN / 2;


// this is for the color block. 
// the bin edges are the boundaries of the bins.
const CIRCULAR_BIN_EDGES = [0, 36, 72, 108, 144, 180];
const CIRCULAR_BIN_LABELS = [
  "0-36 deg",
  "36-72 deg",
  "72-108 deg",
  "108-144 deg",
  "144-180 deg",
];


const ORIENTATION_PERIOD = 180;
const ORIENTATION_BIN_EDGES = [0, 18, 36, 54, 72, 90];
const ORIENTATION_BIN_LABELS = [
  "0-18 deg",
  "18-36 deg",
  "36-54 deg",
  "54-72 deg",
  "72-90 deg",
];


const NUMEROSITY_BIN_EDGES = [0, 0.19, 0.38, 0.57, 0.76, Math.log(NUMEROSITY_MAX / NUMEROSITY_MIN)];
const NUMEROSITY_BIN_LABELS = [
  "0-0.19 log units (~0-7 dots)",
  "0.19-0.38 log units (~7-13 dots)",
  "0.38-0.57 log units (~13-20 dots)",
  "0.57-0.76 log units (~20-29 dots)",
  "0.76-0.95 log units (~29-40 dots)",
];

export const FACTOR_SEQUENCE_SPECS = {
  color: {
    sequenceId: "color-stratified-v1",
    stimulusType: "circular",
    period: 360, // color wraps around the wheel.
    minStimulus: 0,
    maxStimulus: 360,
    binEdges: CIRCULAR_BIN_EDGES,
    binLabels: CIRCULAR_BIN_LABELS,
    repetitionConfig: {
      smallDifferenceThreshold: 18, // 10% of 180 degrees.
      maxConsecutiveSmallDifferences: 3, 
      repeatBackTolerance: 10,
      maxApproxRepeatSpan: 2,
    },
  },
  orientation: {
    sequenceId: "orientation-stratified-v1",
    stimulusType: "circular",
    period: ORIENTATION_PERIOD,
    minStimulus: 0,
    maxStimulus: ORIENTATION_PERIOD,
    binEdges: ORIENTATION_BIN_EDGES,
    binLabels: ORIENTATION_BIN_LABELS,
    repetitionConfig: {
      smallDifferenceThreshold: 9, // 10% of 90deg
      maxConsecutiveSmallDifferences: 3,
      repeatBackTolerance: 5,
      maxApproxRepeatSpan: 2,
    },
  },
  numerosity: {
    sequenceId: "numerosity-stratified-v1",
    stimulusType: "discrete",
    minStimulus: NUMEROSITY_MIN,
    maxStimulus: NUMEROSITY_MAX,
    binEdges: NUMEROSITY_BIN_EDGES,
    binLabels: NUMEROSITY_BIN_LABELS,
    repetitionConfig: {
      smallDifferenceThreshold: 0.12, 
      maxConsecutiveSmallDifferences: 3,
      repeatBackTolerance: 0,
      maxApproxRepeatSpan: 2,
    },
  },
};

export function getSequenceSpec(blockName) {
  const spec = FACTOR_SEQUENCE_SPECS[blockName];
  if (!spec) throw new Error(`Unsupported block for stratified sequence: ${blockName}`);
  return spec;
}

export function computeCircularSignedDifference(currentValue, previousValue, period = 360) {
  return circularError(currentValue, previousValue, period);
}

export function computeNumerosityLogDifference(currentValue, previousValue) {
  if (previousValue === null || previousValue === undefined) return null;
  return Math.log(currentValue / previousValue);
}

export function computePairwiseDifference(blockName, currentValue, previousValue) {
  if (previousValue === null || previousValue === undefined) {
    return {
      signed: null,
      absolute: null,
      logSigned: null,
      logAbsolute: null,
    };
  }
  // find circular signed difference for circular stimuli.
  if (blockName === "color" || blockName === "orientation") {
    const period = getSequenceSpec(blockName).period;
    const signed = computeCircularSignedDifference(currentValue, previousValue, period);
    return {
      signed,
      absolute: Math.abs(signed),
      logSigned: null,
      logAbsolute: null,
    };
  }

  const signed = currentValue - previousValue;
  const logSigned = computeNumerosityLogDifference(currentValue, previousValue);
  return {
    signed,
    absolute: Math.abs(signed),
    logSigned,
    logAbsolute: Math.abs(logSigned),
  };
}

export function getDifferenceMagnitudeForBinning(blockName, difference) {
  if (difference.absolute === null) return null;
  return blockName === "numerosity" ? difference.logAbsolute : difference.absolute;
}

// differene bin will find the bin index for the difference.
export function getDifferenceBin(blockName, currentValue, previousValue) {
  if (previousValue === null || previousValue === undefined) return null;

  const spec = getSequenceSpec(blockName);
  const difference = computePairwiseDifference(blockName, currentValue, previousValue);
  const magnitude = getDifferenceMagnitudeForBinning(blockName, difference);

  for (let index = 0; index < spec.binEdges.length - 1; index += 1) {
    const lower = spec.binEdges[index];
    const upper = spec.binEdges[index + 1];
    const isLast = index === spec.binEdges.length - 2;
    if (magnitude >= lower && (magnitude < upper || (isLast && magnitude <= upper))) {
      return {
        index,
        label: spec.binLabels[index],
        lowerBound: lower,
        upperBound: upper,
      };
    }
  }

  throw new Error(
    `Difference magnitude ${magnitude} for ${blockName} is outside configured bins.`,
  );
}

// validate the stimulus value is within the range of the stimulus type.
export function validateStimulusValue(blockName, stimulusValue) {
  const spec = getSequenceSpec(blockName);

  if (spec.stimulusType === "circular") {
    return stimulusValue >= spec.minStimulus && stimulusValue < spec.maxStimulus;
  }

  return Number.isInteger(stimulusValue)
    && stimulusValue >= spec.minStimulus
    && stimulusValue <= spec.maxStimulus;
}

export function buildSequenceMetadata(blockName, sequenceId, sequenceTrialIndex, currentValue, previousValue) {
  if (sequenceTrialIndex === null) {
    return {
      sequence_id: null,
      sequence_trial_index: null, // the index of the current trial in the sequence.
      previous_stimulus_value: null, // the value of the previous stimulus.
      pairwise_difference_signed: null, // the signed difference between the current and previous stimulus.
      pairwise_difference_abs: null, // the absolute difference between the current and previous stimulus.
      pairwise_difference_log_signed: null, // the signed difference between the current and previous stimulus.
      pairwise_difference_log_abs: null, // the absolute difference between the current and previous stimulus.
      difference_bin_index: null, // the index of the bin for the difference.
      difference_bin_label: null, // the label of the bin for the difference.
      is_precomputed_main_sequence: false, // whether the sequence is a precomputed main sequence.
    };
  }

  const difference = computePairwiseDifference(blockName, currentValue, previousValue);
  const bin = getDifferenceBin(blockName, currentValue, previousValue);

  return {
    sequence_id: sequenceId,
    sequence_trial_index: sequenceTrialIndex,
    previous_stimulus_value: previousValue,
    pairwise_difference_signed: difference.signed,
    pairwise_difference_abs: difference.absolute,
    pairwise_difference_log_signed: difference.logSigned,
    pairwise_difference_log_abs: difference.logAbsolute,
    difference_bin_index: bin?.index ?? null,
    difference_bin_label: bin?.label ?? null,
    is_precomputed_main_sequence: true,
  };
}

export function validateSequence(blockName, sequence) {
  const spec = getSequenceSpec(blockName);

  if (sequence.length !== MAIN_TRIALS_PER_BLOCK) {
    throw new Error(
      `${blockName} sequence must contain ${MAIN_TRIALS_PER_BLOCK} stimuli, received ${sequence.length}.`,
    );
  }

  const binCounts = Array(spec.binLabels.length).fill(0); // count the number of differences in each bin.
  const signedCounts = spec.binLabels.map(() => ({ positive: 0, negative: 0 })); // count the number of positive and negative differences in each bin.
  let consecutiveSmallDifferences = 0; // count the number of consecutive small differences.

  for (let index = 0; index < sequence.length; index += 1) { // loop through the sequence.

    // validate the stimulus value is within the range of the stimulus type.
    if (!validateStimulusValue(blockName, sequence[index])) {
      throw new Error(`${blockName} sequence contains an out-of-range stimulus at index ${index}.`);
    }

    if (index === 0) continue; // skip the first trial.

    const previousValue = sequence[index - 1];
    const currentValue = sequence[index];
    const difference = computePairwiseDifference(blockName, currentValue, previousValue);
    const magnitude = getDifferenceMagnitudeForBinning(blockName, difference);
    const bin = getDifferenceBin(blockName, currentValue, previousValue);

    binCounts[bin.index] += 1; // count the number of differences in the bin.
    if (difference.signed >= 0) signedCounts[bin.index].positive += 1; // count the number of positive differences in the bin.
    if (difference.signed < 0) signedCounts[bin.index].negative += 1; // count the number of negative differences in the bin.

    // if the magnitude is less than the small difference threshold, count the number of consecutive small differences.
    // if the number of consecutive small differences is greater than the max consecutive small differences, throw an error.
    // otherwise, reset the number of consecutive small differences.
    if (magnitude < spec.repetitionConfig.smallDifferenceThreshold) {
      consecutiveSmallDifferences += 1;
      if (consecutiveSmallDifferences > spec.repetitionConfig.maxConsecutiveSmallDifferences) {
        throw new Error(`${blockName} sequence contains too many similar consecutive transitions.`);
      }
    } else {
      consecutiveSmallDifferences = 0;
    }

    const repeatIndex = index - spec.repetitionConfig.maxApproxRepeatSpan; // check for approximate short-lag repeats.
    if (repeatIndex >= 0) {
      const repeatDifference = computePairwiseDifference(blockName, currentValue, sequence[repeatIndex]);
      const repeatMagnitude = getDifferenceMagnitudeForBinning(blockName, repeatDifference);
      if (repeatMagnitude <= spec.repetitionConfig.repeatBackTolerance) {
        throw new Error(`${blockName} sequence contains an approximate short-lag repeat.`);
      }
    }
  }

  binCounts.forEach((count, index) => { // validate the number of differences in each bin.
    if (count !== DIFFERENCES_PER_BIN) { // expected the number of differences in each bin to be the same.
      throw new Error(`${blockName} bin ${index} expected ${DIFFERENCES_PER_BIN} differences, received ${count}.`);
    }
    if (signedCounts[index].positive !== TARGET_SIGN_COUNT_PER_BIN) { // expected the number of positive differences in each bin to be the same.
      throw new Error(`${blockName} bin ${index} expected ${TARGET_SIGN_COUNT_PER_BIN} positive differences.`);
    }
    if (signedCounts[index].negative !== TARGET_SIGN_COUNT_PER_BIN) { // expected the number of negative differences in each bin to be the same.
      throw new Error(`${blockName} bin ${index} expected ${TARGET_SIGN_COUNT_PER_BIN} negative differences.`);
    }
  });

  return {
    sequenceId: spec.sequenceId,
    stimulusCount: sequence.length,
    differenceCount: sequence.length - 1,
    binCounts,
    signedCounts,
  };
}
