/*
  Builds the mask for the stimulus.
  This mask is shown after the stimulus is shown to the participant.
  This mask is a simple gaussian blur applied to a noise canvas with a radial gradient.
*/

import {
  APERTURE_BORDER_COLOR,
  APERTURE_BORDER_PX,
  MASK_BLUR_PX,
  STIMULUS_DIAMETER_PX,
} from "./config.js";
import { buildApertureShellHtml, buildCanvasFixationStimulus } from "./stimuli.js";
import { viewportPositionToCanvasOffset } from "./utils.js";

export function buildMaskNoiseDataUrl(size = STIMULUS_DIAMETER_PX) {
  const noiseScale = 18;
  const noiseWidth = Math.ceil(size / noiseScale);
  const noiseHeight = Math.ceil(size / noiseScale);

  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext("2d");

  if (!ctx) return null;

  const noiseCanvas = document.createElement("canvas");
  noiseCanvas.width = noiseWidth;
  noiseCanvas.height = noiseHeight;
  const noiseCtx = noiseCanvas.getContext("2d");

  if (!noiseCtx) return null;

  const noiseImage = noiseCtx.createImageData(noiseWidth, noiseHeight);
  for (let i = 0; i < noiseWidth * noiseHeight; i += 1) {
    const index = i * 4;
    const value = 128 + Math.round((Math.random() - 0.5) * 120);
    noiseImage.data[index] = value;
    noiseImage.data[index + 1] = value;
    noiseImage.data[index + 2] = value;
    noiseImage.data[index + 3] = 255;
  }

  noiseCtx.putImageData(noiseImage, 0, 0);
  ctx.clearRect(0, 0, size, size);
  ctx.imageSmoothingEnabled = true;
  ctx.filter = `blur(${MASK_BLUR_PX}px)`;
  ctx.save();
  // Clip the blurred noise to the circular stimulus aperture before we apply
  // the radial fade, so the mask stays aligned with the stimulus boundary.
  ctx.beginPath();
  ctx.arc(size / 2, size / 2, size / 2, 0, Math.PI * 2);
  ctx.closePath();
  ctx.clip();
  ctx.drawImage(noiseCanvas, 0, 0, size, size);
  ctx.restore();
  ctx.filter = "none";

  const gradient = ctx.createRadialGradient(
    size / 2,
    size / 2,
    size * 0.08,
    size / 2,
    size / 2,
    size / 2,
  );
  gradient.addColorStop(0, "rgba(255,255,255,0.9)");
  gradient.addColorStop(0.35, "rgba(255,255,255,0.5)");
  gradient.addColorStop(0.7, "rgba(255,255,255,0.18)");
  gradient.addColorStop(1, "rgba(255,255,255,0)");
  // Keep the mask strongest near the center and feather it out toward the
  // edge so it reads like a soft noise patch rather than a hard disk.
  ctx.globalCompositeOperation = "destination-in";
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, size, size);
  ctx.globalCompositeOperation = "source-over";

  return canvas.toDataURL();
}

export function buildMaskHtml(position) {
  const noiseUrl = buildMaskNoiseDataUrl();
  if (!noiseUrl) {
    return buildApertureShellHtml(position, "background:#808080;", "");
  }

  return buildApertureShellHtml(
    position,
    `
      background-color:#808080;
      background-image:url(${noiseUrl});
      background-size:cover;
      background-position:center;
    `,
    "",
  );
}


// this is a helper so we can use the same mask for the orientation stimulus.
// since the orientation stimulus is procedurally generated by the plugin, 
// there was a small shift in the mask and the shell, so this will be used
// to ensure the mask is aligned with the stimulus and no kind of movement is introduced.
export function buildOrientationMaskPsychophysicsStimuli(position, options = {}) {
  const { includeFixation = true } = options;
  const canvasOffset = viewportPositionToCanvasOffset(position);
  const noiseUrl = buildMaskNoiseDataUrl();
  const borderRadius = STIMULUS_DIAMETER_PX / 2 - APERTURE_BORDER_PX / 2;
  const apertureRadius = borderRadius - APERTURE_BORDER_PX / 2;

  // Mirror the orientation stimulus stack inside the psychophysics canvas:
  // gray background circle, noise image centered at the same coordinates,
  // then the aperture border on top.
  const stimuli = [
    {
      obj_type: "circle",
      origin_center: true,
      startX: canvasOffset.x,
      startY: canvasOffset.y,
      radius: apertureRadius,
      line_width: 0,
      fill_color: "#808080",
    },
  ];

  if (noiseUrl) {
    stimuli.push({
      obj_type: "image",
      origin_center: true,
      startX: canvasOffset.x,
      startY: canvasOffset.y,
      file: noiseUrl,
      image_width: STIMULUS_DIAMETER_PX,
    });
  }

  stimuli.push({
    obj_type: "circle",
    origin_center: true,
    startX: canvasOffset.x,
    startY: canvasOffset.y,
    radius: borderRadius,
    line_width: APERTURE_BORDER_PX,
    line_color: APERTURE_BORDER_COLOR,
  });

  if (includeFixation) {
    stimuli.push(buildCanvasFixationStimulus());
  }

  return stimuli;
}
